In [2]:
from time import time
import numpy as np

In [8]:
class Sort(object):
    def __init__(self):
        self.__example = []

    @property
    def output(self):
        return self.__example

    def random_list(self, lenght):
        self.__example = np.random.randint(-1000, 1000, lenght)
        return self.__example

    def sorted_list(self, list_):
        return self.bubble_sort_for(list_)[0]

    def reversed_sorted_list(self, list_):
        return self.bubble_sort_for(list_)[0][::-1]

    def partially_sorted_list(self, list_):
        intermediate_list = sorted(list_)[:-(len(list_) // 10)]
        additional_list = np.random.randint(-1000, 1000, len(list_) // 10)
        return np.append(intermediate_list, additional_list)

    def bubble_sort_while(self, list_):
        index, flag = 0, False
        start_time = time()
        while True:
            if index == len(list_) - 1 and flag == True:
                index, flag = 0, False
            if index == len(list_) - 2 and flag == False:
                break
            if list_[index] > list_[index + 1]:
                list_[index], list_[index + 1] = list_[index + 1], list_[index]
                flag = True
            index += 1
        end_time = time()
        return list_, end_time - start_time

    def bubble_sort_for(self, list_):
        start_time = time()
        for i in range(len(list_)):
            for j in range(len(list_) - i - 1):
                if list_[j] > list_[j + 1]:
                    list_[j], list_[j + 1] = list_[j + 1], list_[j]
        end_time = time()
        return list_, end_time - start_time

    def rock_bubble_sort(self, list_):
        left_side, right_side = 0, len(list_) - 1

        start_time = time()

        while left_side < right_side:
            for i in range(right_side):
                if list_[i] > list_[i + 1]:
                    list_[i], list_[i + 1] = list_[i + 1], list_[i]
            right_side -= 1

            for i in range(right_side, left_side + 1, -1):
                if list_[i] < list_[i - 1]:
                    list_[i], list_[i - 1] = list_[i - 1], list_[i]
            left_side += 1

        end_time = time()
        return list_, end_time - start_time

    def quick_sort(self, list_):
        if len(list_) <= 1:
            return list_

        else:
            central = list_[0]
            left_side = [element for element in list_ if element < central]
            right_side = [element for element in list_ if element > central]
            return self.quick_sort(left_side) + [central] + self.quick_sort(right_side)
    
    def quick_sort_for_sorted(self, list_):
        if len(list_) <= 1:
            return list_

        else:
            central = list_[len(list_) // 2]
            left_side = [element for element in list_ if element < central]
            right_side = [element for element in list_ if element > central]
            return self.quick_sort(left_side) + [central] + self.quick_sort(right_side)
    
    def selection_sort(self, list_):
        for i in range(len(list_)):
            largest = i
            for j in range(i + 1, len(list_)):
                if list_[j] > list_[largest]:
                    largest = j
            list_[i], list_[largest] = list_[largest], list_[i]
        return list_
    
    def modified_selection_sort(self, list_):
        for i in range(len(list_) - 1, 0, -1):
            largest = i
            for j in range(i - 1, 0, -1):
                if list_[j] > list_[largest]:
                    largest = j
            list_[i], list_[largest] = list_[largest], list_[i]
        return list_

10 номер

In [19]:
# создаем список рандомных значений
random_example = example.random_list(20)
random_example

array([ 296,  116,  348,  998,  614, -777, -456,   -1,  781,  489, -956,
       -564,  123, -802,  205,  871,  854, -415,   63, -875])

In [20]:
# 1 функция
example.sorted_list(random_example)

array([-956, -875, -802, -777, -564, -456, -415,   -1,   63,  116,  123,
        205,  296,  348,  489,  614,  781,  854,  871,  998])

In [21]:
# 2 функция
example.reversed_sorted_list(random_example)

array([ 998,  871,  854,  781,  614,  489,  348,  296,  205,  123,  116,
         63,   -1, -415, -456, -564, -777, -802, -875, -956])

In [22]:
# 3 функция
example.reversed_sorted_list(random_example)

array([ 998,  871,  854,  781,  614,  489,  348,  296,  205,  123,  116,
         63,   -1, -415, -456, -564, -777, -802, -875, -956])

In [23]:
# 4 функция
example.partially_sorted_list(random_example)

array([-956, -875, -802, -777, -564, -456, -415,   -1,   63,  116,  123,
        205,  296,  348,  489,  614,  781,  854, -448,  -86])

12 номер

In [25]:
example.rock_bubble_sort(random_example)[0]

array([-956, -875, -802, -777, -564, -456, -415,   -1,   63,  116,  123,
        205,  296,  348,  489,  614,  781,  854,  871,  998])

14 номер

случайный список

In [15]:
start_time = time()
example.bubble_sort_for(example.random_list(10000))
end_time = time()
print(end_time - start_time)

49.08084416389465


(сортированный список)

In [16]:
test_time = sorted(example.random_list(10000))
start_time = time()
example.bubble_sort_for(test_time)
end_time = time()
print(end_time - start_time)

14.880959272384644


(перевернутый отсортированный список)

In [17]:
test_time = sorted(example.random_list(10000))[::-1]
start_time = time()
example.bubble_sort_for(test_time)
end_time = time()
print(end_time - start_time)

22.836506128311157


(частично отсортированный список)

In [12]:
test_time = example.partially_sorted_list(example.random_list(10000))
start_time = time()
example.quick_sort(test_time)
end_time = time()
print(end_time - start_time)

0.8208422660827637


rock_bubble_sort - сортировка камешек - пузырек реализованная в импровизированным мной представлением

случайный список

In [13]:
start_time = time()
example.rock_bubble_sort(example.random_list(10000))
end_time = time()
print(end_time - start_time)

21.205727577209473


отсортированный список

In [14]:
test_time = sorted(example.random_list(10000))
start_time = time()
example.rock_bubble_sort(test_time)
end_time = time()
print(end_time - start_time)

5.807560682296753


(перевернутый отсортированный список)

In [31]:
test_time = example.random_list(10000)
start_time = time()
example.selection_sort(test_time)
end_time = time()
print(end_time - start_time)

9.501111507415771


15 номер

In [32]:
test_time = sorted(example.random_list(10000))
start_time = time()
example.selection_sort(test_time)
end_time = time()
print(end_time - start_time)

3.3829569816589355


In [37]:
test_time = example.random_list(10000)
start_time = time()
example.modified_selection_sort(test_time)
end_time = time()
print(end_time - start_time)

9.5844087600708


In [38]:
test_time = sorted(example.random_list(10000))
start_time = time()
example.modified_selection_sort(test_time)
end_time = time()
print(end_time - start_time)

3.528132915496826


частично отсортированный список

In [21]:
test_time = example.partially_sorted_list(example.random_list(100000))
start_time = time()
example.quick_sort(test_time)
end_time = time()
print(end_time - start_time)

9.176163673400879


16 номер

Реализовать быструю сортировку с возможностью подсчета операций. Сравнить производительность алгоритма на случайных и упорядоченных (и почти упорядоченных) данных.

In [17]:
print(example.quick_sort(random_example))

[-851, -810, -714, -684, -458, -313, -240, -82, 135, 137, 362, 376, 418, 425, 431, 456, 493, 510, 646, 953]


(случайный список)

In [18]:
start_time = time()
example.quick_sort(example.random_list(100000))
end_time = time()
print(end_time - start_time)

0.132645845413208


(отсортированный список)

In [19]:
test_time = sorted(example.random_list(100000))
start_time = time()
example.quick_sort(test_time)
end_time = time()
print(end_time - start_time)

14.657094240188599


(перевернутый отсортированный список)

In [20]:
test_time = sorted(example.random_list(100000))[::-1]
start_time = time()
example.quick_sort(test_time)
end_time = time()
print(end_time - start_time)

14.168990850448608


In [16]:
test_time = example.partially_sorted_list(example.random_list(10000))
start_time = time()
example.rock_bubble_sort(test_time)
end_time = time()
print(end_time - start_time)

15.355230569839478


In [15]:
test_time = sorted(example.random_list(10000))[::-1]
start_time = time()
example.rock_bubble_sort(test_time)
end_time = time()
print(end_time - start_time)

12.269426345825195


(частично отсортированный список)